import os
from pathlib import Path

# UID-based vault folder schema (Genesis Phase 0)
vault_structure = {
    "SS-TM_00-00_system-core": [],
    "GT-WK_00-00_gateway-inputs": [],
    "XP-PR_00-00_experiments-live": ["UID_MAP.md"],
    "CR-TV_00-00_creative-systems": ["visual/", "sonic/", "mythos/"],
    "FR-GM_00-00_fragments-memory": ["dreams/", "revisions/", "traces/"],
    "PD-GG_00-00_guidance-protocols": ["courses/", "feedback/", "sops/"],
    "PB-RC_00-00_observation-logs": ["grants/", "publications/", "folios/"],
    "RC-VK_00-00_archives": ["exports/", "fossils/", "legacy/"],
    "FL-TR_00-00_anomaly-stream": ["to-process/", "inbox/", "misc/"],
    "NR-TH_00-00_narrative-threads": ["epics/", "fragments/", "prototypes/"],
    "SB-ML_00-00_symbol-codex": ["uid-maps/", "color-systems/", "glyphs/"],
    "MT-PR_00-00_meta-operations": ["logs/", "design-dev/", "changelogs/"],
    "PR-JC_00-00_projects-external": ["clients/", "collabs/", "deliverables/"],
    "WR-KS_00-00_workshop-series": ["events/", "groups/", "talks/"],
    "CL-ND_00-00_spawn-templates": ["use-cases/", "forks/", "reset-states/"],
    "GM-DS_00-00_game-design-sandbox": [
        "GM-LG_01-00_logic-mechanics/",
        "PL-YR_01-00_player-archetypes/",
        "RL-ES_01-00_rule-scripts/",
        "WM-AP_01-00_world-maps/",
        "AS-ST_01-00_assets-ui/",
        "NX-ST_01-00_nexus-links/"
    ]
}

def initialize_vault(base_path="4_S0VRC3_vault"):
    print(f"Creating vault at: {base_path}")
    os.makedirs(base_path, exist_ok=True)

    for folder, contents in vault_structure.items():
        folder_path = os.path.join(base_path, folder)
        os.makedirs(folder_path, exist_ok=True)
        Path(os.path.join(folder_path, "README.md")).write_text(f"# {folder}\n\nSystem folder `{folder}`.\n")
        Path(os.path.join(folder_path, "index.md")).write_text(f"# index.md\n\nThis is the index page for `{folder}`.\n")

        for item in contents:
            sub_path = os.path.join(folder_path, item)
            if item.endswith("/"):
                os.makedirs(sub_path, exist_ok=True)
                Path(os.path.join(sub_path, "README.md")).write_text(f"# {item.strip('/')}\n\nSubdomain of `{folder}`.\n")
            elif item.endswith(".md"):
                Path(sub_path).write_text(f"# {item}\n\nAutogenerated placeholder in `{folder}`.\n")

    print("Vault structure initialized.")

if __name__ == "__main__":
    initialize_vault()
